# Stack-aware remediation templates. Each finding kind maps to a generic
# fallback plus optional per-stack overrides selected via fingerprint.detect().

TEMPLATES = {
    "idor": {
        "generic": {"summary": "Enforce object-level authorization on every resource lookup.", "language": "Generic", "codeExample": "resource = get_owned_resource(current_user.id, resource_id)  # verify ownership before returning", "recommendations": ["Authorize the authenticated principal against the requested object owner/tenant.", "Return the same generic response for unauthorized object IDs where practical.", "Add regression tests for horizontal and vertical access control."]},
        "fastapi": {"summary": "Enforce object-level authorization in the FastAPI path operation, not just at the router level.", "language": "Python/FastAPI", "codeExample": "@router.get('/users/{user_id}')\nasync def get_user(user_id: str, current=Depends(get_current_user)):\n    if user_id != current.id and not current.is_admin:\n        raise HTTPException(status_code=404)  # 404, not 403 — avoid confirming existence\n    return await db_get_user(user_id)", "recommendations": ["Check ownership inside the handler, never rely on the client-supplied ID alone.", "Prefer 404 over 403 for cross-tenant lookups to avoid enumeration.", "Add a pytest case per role asserting cross-object access is denied."]},
        "express": {"summary": "Enforce object-level authorization in Express middleware/route handlers.", "language": "JavaScript/Express", "codeExample": "app.get('/api/v1/users/:id', requireAuth, async (req, res) => {\n  if (req.params.id !== req.user.id && !req.user.isAdmin) return res.sendStatus(404);\n  res.json(await Users.findById(req.params.id));\n});", "recommendations": ["Never trust :id params for authorization decisions.", "Centralize ownership checks in reusable middleware.", "Add integration tests for cross-user object access."]},
        "django": {"summary": "Use Django's permission/queryset filtering so lookups are scoped to the requesting user.", "language": "Python/Django", "codeExample": "def get_queryset(self):\n    return Model.objects.filter(owner=self.request.user)  # scope, don't post-filter", "recommendations": ["Scope querysets by owner instead of filtering after fetch.", "Use DRF permission classes (IsOwnerOrAdmin) consistently.", "Add tests asserting 404 for another user's object id."]},
    },
    "sqli": {
        "generic": {"summary": "Use parameterized queries and reject unexpected input types.", "language": "Generic", "codeExample": "db.execute('SELECT * FROM items WHERE id = ?', [item_id])", "recommendations": ["Never concatenate request parameters into SQL.", "Use ORM/query-builder parameter binding.", "Run database users with least privilege."]},
        "fastapi": {"summary": "Use SQLAlchemy bound parameters; never f-string user input into SQL.", "language": "Python/SQLAlchemy", "codeExample": "db.execute(text('SELECT * FROM items WHERE id = :id'), {'id': item_id})", "recommendations": ["Never concatenate request parameters into SQL.", "Prefer ORM query methods over raw text() where possible.", "Run the DB user with least privilege (no DDL rights)."]},
        "express": {"summary": "Use a parameterized query builder (e.g. `pg`/`knex`) instead of string concatenation.", "language": "JavaScript/Node", "codeExample": "await pool.query('SELECT * FROM items WHERE id = $1', [itemId]);", "recommendations": ["Never build SQL with template literals from request input.", "Use knex/Prisma/parameterized `pg` queries exclusively.", "Enable query logging in staging to catch string-built SQL in review."]},
    },
    "xss": {
        "generic": {"summary": "Contextually encode untrusted output and avoid unsafe DOM sinks.", "language": "Generic", "codeExample": "output = escape_html(user_controlled_value)", "recommendations": ["Avoid unsafe raw-HTML injection unless content is strictly sanitized.", "Apply output encoding appropriate to HTML/URL/JS contexts.", "Deploy a restrictive Content-Security-Policy."]},
        "nextjs": {"summary": "Avoid dangerouslySetInnerHTML; let React's default escaping handle output.", "language": "TypeScript/React", "codeExample": "<div>{userControlledValue}</div>  // never <div dangerouslySetInnerHTML={{__html: userControlledValue}} />", "recommendations": ["Avoid dangerouslySetInnerHTML unless content is passed through a sanitizer (e.g. DOMPurify).", "Apply output encoding appropriate to HTML/URL/JS contexts.", "Deploy a restrictive Content-Security-Policy (script-src 'self')."]},
    },
    "cors": {
        "generic": {"summary": "Allow only trusted origins and avoid credentialed wildcard CORS.", "language": "Generic", "codeExample": "allowed_origins = ['https://trusted.example']", "recommendations": ["Do not reflect arbitrary Origin headers.", "Keep allowed origins explicit and environment-specific.", "Review credentialed cross-origin endpoints separately."]},
        "fastapi": {"summary": "Pin CORSMiddleware to an explicit origin allow-list; never reflect Origin with credentials.", "language": "Python/FastAPI", "codeExample": "app.add_middleware(CORSMiddleware, allow_origins=['https://trusted.example'], allow_credentials=True, allow_methods=['GET','POST'])", "recommendations": ["Never set allow_origins=['*'] together with allow_credentials=True.", "Keep the allow-list environment-specific (dev/stage/prod).", "Audit which endpoints actually need credentialed cross-origin access."]},
        "express": {"summary": "Configure the `cors` middleware with an explicit origin allow-list function.", "language": "JavaScript/Express", "codeExample": "app.use(cors({ origin: ['https://trusted.example'], credentials: true }));", "recommendations": ["Never use origin: '*' together with credentials: true.", "Validate Origin against an allow-list, not a regex that can be bypassed.", "Log rejected CORS attempts for monitoring."]},
    },
    "rate-limit": {
        "generic": {"summary": "Apply endpoint-specific throttling and account lockout controls.", "language": "Generic", "codeExample": "rate_limit(endpoint='/auth/token', max_requests=5, window_seconds=60)", "recommendations": ["Rate-limit authentication and high-cost endpoints.", "Use progressive backoff and monitoring.", "Do not rely on client-side throttling."]},
        "fastapi": {"summary": "Apply `slowapi`/Redis-backed throttling to authentication endpoints specifically.", "language": "Python/FastAPI", "codeExample": "@limiter.limit('5/minute')\n@router.post('/auth/token')\nasync def login(...): ...", "recommendations": ["Rate-limit by IP + account identifier, not IP alone.", "Add progressive backoff/lockout after repeated failures.", "Alert on abnormal authentication request volume."]},
        "express": {"summary": "Apply `express-rate-limit` (Redis store in production) to auth routes.", "language": "JavaScript/Express", "codeExample": "app.post('/api/v1/auth/token', rateLimit({ windowMs: 60000, max: 5 }), loginHandler);", "recommendations": ["Use a shared store (Redis) so limits hold across instances.", "Rate-limit by account identifier as well as IP.", "Return 429 with Retry-After, not a silent pass-through."]},
    },
    "headers": {"generic": {"summary": "Deploy baseline browser security headers.", "language": "HTTP", "codeExample": "Content-Security-Policy: default-src 'self'\nX-Content-Type-Options: nosniff\nReferrer-Policy: strict-origin-when-cross-origin\nX-Frame-Options: DENY", "recommendations": ["Set CSP, X-Content-Type-Options, Referrer-Policy and frame protections.", "Review CSP for actual application dependencies before enforcing.", "Re-test after deployment since CSP is easy to misconfigure."]}},
    "tls": {"generic": {"summary": "Use modern TLS configuration and enforce HTTPS.", "language": "Nginx", "codeExample": "ssl_protocols TLSv1.2 TLSv1.3;\nadd_header Strict-Transport-Security \"max-age=63072000; includeSubDomains\" always;", "recommendations": ["Disable obsolete protocol versions (TLS 1.0/1.1) and weak cipher suites.", "Enable HSTS only after validating full HTTPS coverage.", "Automate certificate renewal and monitor expiry."]}},
    "privacy": {"generic": {"summary": "Minimize sensitive fields returned by APIs and client storage.", "language": "Generic", "codeExample": "return public_view(user)  # explicit allow-list, not the raw ORM object", "recommendations": ["Use explicit response schemas/serializers, never return the raw model.", "Do not expose secrets, password hashes or unrelated user records.", "Review localStorage/sessionStorage for sensitive material."]}, "fastapi": {"summary": "Return an explicit Pydantic response_model that excludes internal fields.", "language": "Python/FastAPI", "codeExample": "@router.get('/users/{id}', response_model=UserPublic)\nasync def get_user(id: str): ...  # UserPublic has no password_hash/token fields", "recommendations": ["Always set response_model explicitly; never return the DB row directly.", "Keep an internal vs public schema pair per resource.", "Add a test asserting sensitive keys never appear in list/detail responses."]}},
    "client": {"generic": {"summary": "Remove unsafe client-side execution sinks and secrets.", "language": "TypeScript", "codeExample": "element.textContent = value;  // never element.innerHTML = value", "recommendations": ["Avoid eval/new Function and unsafe HTML injection.", "Never ship private API credentials in client bundles.", "Run a secret scanner (e.g. trufflehog) on the built bundle in CI."]}},
    "jwt": {"generic": {"summary": "Reject unsigned/none-alg tokens and pin the expected signing algorithm.", "language": "Generic", "codeExample": "jwt.decode(token, key, algorithms=['RS256'])  # pin algorithms explicitly, never accept 'none'", "recommendations": ["Explicitly pin allowed algorithms server-side; never trust the token's own `alg` header.", "Reject tokens with `alg: none` unconditionally.", "Rotate signing keys and use short-lived access tokens with refresh rotation."]}},
    "exposure": {"generic": {"summary": "Remove development/backup artifacts from the deployed environment.", "language": "DevOps", "codeExample": "# in deploy pipeline\nrm -rf .git .env*.bak *.zip *.sql.bak  # before building the production image", "recommendations": ["Exclude VCS metadata and backup/config files from deployment artifacts.", "Add a CI step that fails the build if common sensitive filenames are present.", "Restrict directory listing at the web-server level."]}},
    "mass-assignment": {"generic": {"summary": "Bind requests to an explicit allow-listed schema, never the full model.", "language": "Generic", "codeExample": "update_fields = {'name': body.name, 'email': body.email}  # explicit allow-list, not **body", "recommendations": ["Never bind request bodies directly onto ORM models (no `Model(**request.json)`).", "Use an explicit input schema per endpoint that excludes privileged fields (role, isAdmin).", "Add a test that a privilege-escalation field in the body is silently ignored."]}},
    "redirect": {"generic": {"summary": "Validate redirect targets against an allow-list instead of trusting client input.", "language": "Generic", "codeExample": "if target not in ALLOWED_REDIRECTS: target = '/'  # never redirect(request.args['next']) directly", "recommendations": ["Only allow redirects to relative, known-safe paths or an explicit allow-list of hosts.", "Never pass a raw query parameter straight into a redirect call.", "Log rejected redirect attempts for monitoring."]}},
}


def get(kind: str, stack: str = "generic"):
    entry = TEMPLATES.get(kind) or TEMPLATES["headers"]
    return entry.get(stack) or entry.get("generic") or next(iter(entry.values()))
